name: Project Tests
on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6.15
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.15
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install -r requirements.txt
      - name: Test with pytest
        run: pytest -vv
